<?xml version="1.0" encoding="utf-8"?><Database Name="APPDISTRIPRUEBA" Class="BASEDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-5T0Q15T\BASE;Initial Catalog=APPDISTRIPRUEBA;Integrated Security=True" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="APPDISTRIPRUEBAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BEBIDA" Member="BEBIDA">
    <Type Name="BEBIDA">
      <Column Name="ID_BEB" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOM_BEB" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IMG_BEBIDA" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="BEBIDA_DETALLE_BEBIDA" Member="DETALLE_BEBIDA" ThisKey="ID_BEB" OtherKey="ID_REC_PER" Type="DETALLE_BEBIDA" />
      <Association Name="BEBIDA_MENU" Member="MENU" ThisKey="ID_BEB" OtherKey="ID_BEB_MEN" Type="MENU" />
    </Type>
  </Table>
  <Table Name="dbo.DETALLE_BEBIDA" Member="DETALLE_BEBIDA">
    <Type Name="DETALLE_BEBIDA">
      <Column Name="ID_DET_REC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_REC_PER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_ING_USA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BEBIDA_DETALLE_BEBIDA" Member="BEBIDA" ThisKey="ID_REC_PER" OtherKey="ID_BEB" Type="BEBIDA" IsForeignKey="true" />
      <Association Name="INGREDIENTES_DETALLE_BEBIDA" Member="INGREDIENTES" ThisKey="ID_ING_USA" OtherKey="ID_ING" Type="INGREDIENTES" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DETALLE_POSTRE" Member="DETALLE_POSTRE">
    <Type Name="DETALLE_POSTRE">
      <Column Name="ID_DET_REC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_REC_PER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_ING_USA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="INGREDIENTES_DETALLE_POSTRE" Member="INGREDIENTES" ThisKey="ID_ING_USA" OtherKey="ID_ING" Type="INGREDIENTES" IsForeignKey="true" />
      <Association Name="POSTRE_DETALLE_POSTRE" Member="POSTRE" ThisKey="ID_REC_PER" OtherKey="ID_POS" Type="POSTRE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DETALLE_SEGUNDO" Member="DETALLE_SEGUNDO">
    <Type Name="DETALLE_SEGUNDO">
      <Column Name="ID_DET_REC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_REC_PER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_ING_USA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="INGREDIENTES_DETALLE_SEGUNDO" Member="INGREDIENTES" ThisKey="ID_ING_USA" OtherKey="ID_ING" Type="INGREDIENTES" IsForeignKey="true" />
      <Association Name="SEGUNDO_DETALLE_SEGUNDO" Member="SEGUNDO" ThisKey="ID_REC_PER" OtherKey="ID_SEG" Type="SEGUNDO" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DETALLE_SOPA" Member="DETALLE_SOPA">
    <Type Name="DETALLE_SOPA">
      <Column Name="ID_DET_REC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_REC_PER" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_ING_USA" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="INGREDIENTES_DETALLE_SOPA" Member="INGREDIENTES" ThisKey="ID_ING_USA" OtherKey="ID_ING" Type="INGREDIENTES" IsForeignKey="true" />
      <Association Name="SOPA_DETALLE_SOPA" Member="SOPA" ThisKey="ID_REC_PER" OtherKey="ID_SOP" Type="SOPA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.INGREDIENTES" Member="INGREDIENTES">
    <Type Name="INGREDIENTES">
      <Column Name="ID_ING" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOM_ING" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="INGREDIENTES_DETALLE_BEBIDA" Member="DETALLE_BEBIDA" ThisKey="ID_ING" OtherKey="ID_ING_USA" Type="DETALLE_BEBIDA" />
      <Association Name="INGREDIENTES_DETALLE_POSTRE" Member="DETALLE_POSTRE" ThisKey="ID_ING" OtherKey="ID_ING_USA" Type="DETALLE_POSTRE" />
      <Association Name="INGREDIENTES_DETALLE_SEGUNDO" Member="DETALLE_SEGUNDO" ThisKey="ID_ING" OtherKey="ID_ING_USA" Type="DETALLE_SEGUNDO" />
      <Association Name="INGREDIENTES_DETALLE_SOPA" Member="DETALLE_SOPA" ThisKey="ID_ING" OtherKey="ID_ING_USA" Type="DETALLE_SOPA" />
    </Type>
  </Table>
  <Table Name="dbo.MENU" Member="MENU">
    <Type Name="MENU">
      <Column Name="ID_MEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_SOP_MEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_SEG_MEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_BEB_MEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_POS_MEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FECHA_MEN" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="BEBIDA_MENU" Member="BEBIDA" ThisKey="ID_BEB_MEN" OtherKey="ID_BEB" Type="BEBIDA" IsForeignKey="true" />
      <Association Name="POSTRE_MENU" Member="POSTRE" ThisKey="ID_POS_MEN" OtherKey="ID_POS" Type="POSTRE" IsForeignKey="true" />
      <Association Name="SEGUNDO_MENU" Member="SEGUNDO" ThisKey="ID_SEG_MEN" OtherKey="ID_SEG" Type="SEGUNDO" IsForeignKey="true" />
      <Association Name="SOPA_MENU" Member="SOPA" ThisKey="ID_SOP_MEN" OtherKey="ID_SOP" Type="SOPA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.POSTRE" Member="POSTRE">
    <Type Name="POSTRE">
      <Column Name="ID_POS" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOM_POS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IMG_POSTRE" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="POSTRE_DETALLE_POSTRE" Member="DETALLE_POSTRE" ThisKey="ID_POS" OtherKey="ID_REC_PER" Type="DETALLE_POSTRE" />
      <Association Name="POSTRE_MENU" Member="MENU" ThisKey="ID_POS" OtherKey="ID_POS_MEN" Type="MENU" />
    </Type>
  </Table>
  <Table Name="dbo.SEGUNDO" Member="SEGUNDO">
    <Type Name="SEGUNDO">
      <Column Name="ID_SEG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOM_SEG" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IMG_SEGUNDO" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="SEGUNDO_DETALLE_SEGUNDO" Member="DETALLE_SEGUNDO" ThisKey="ID_SEG" OtherKey="ID_REC_PER" Type="DETALLE_SEGUNDO" />
      <Association Name="SEGUNDO_MENU" Member="MENU" ThisKey="ID_SEG" OtherKey="ID_SEG_MEN" Type="MENU" />
    </Type>
  </Table>
  <Table Name="dbo.SOPA" Member="SOPA">
    <Type Name="SOPA">
      <Column Name="ID_SOP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NOM_SOP" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IMG_SOPA" Type="System.Data.Linq.Binary" DbType="Image NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="SOPA_DETALLE_SOPA" Member="DETALLE_SOPA" ThisKey="ID_SOP" OtherKey="ID_REC_PER" Type="DETALLE_SOPA" />
      <Association Name="SOPA_MENU" Member="MENU" ThisKey="ID_SOP" OtherKey="ID_SOP_MEN" Type="MENU" />
    </Type>
  </Table>
</Database>